### ISSUE TITLE
Further support for `IO` objects

### ISSUE THREAD

**Issue by kimikage** [GunnarFarneback/Inflate.jl#19]
I don't understand the history of this package, but this package handles `Vector{UInt8}` at a low level.
However, much of what this package does should already be provided at a high level by `IO` objects such as `IOBuffer`.

**Comment by kimikage** [comment]
https://github.com/GunnarFarneback/Inflate.jl/blob/ed24b3286145fdb355b8972fcf36fb4c234354c6/src/Inflate.jl#L255-L263

One of the performance bottlenecks is the `append!` there. Handling variable length data is what `IOBuffer` is good at.

**Comment by GunnarFarneback** [comment]
This is the history: https://gist.github.com/GunnarFarneback/8254567

It was initially written ten years ago for Julia 0.2 because at the time it was too difficult to get libz working for Windows and it was much easier to write a Julia implementation. It was later converted to a package and the streaming support was added when LightGraphs wanted to make use of it.

**Comment by kimikage** [comment]
I showed an example of using `IO` objects in PR#22.
We can re-open this.
